### ISSUE TITLE
Tests should not be included in dist

### ISSUE THREAD

**Issue by angrykoala** [foundernest/simple-queue-decorator#14]
Tests are currently compiled and included in dist. This should not happen. One possible approach would be:

1. Set tsconfig to only compile index.ts and folder src (or ignore tests folder)
2. Use ts-node along with mocha (`mocha -r ts-node/register`) to execute .ts tests without explicit compilation

> This issue must be merged into dev branch

**Comment by Agreon** [comment]
I would like to help you with that :)
